-- Drop tables
DROP TABLE T_CITY CASCADE;
DROP TABLE T_LOCATION CASCADE;
DROP TABLE T_EVENT CASCADE;
DROP TABLE T_ORDER CASCADE;
DROP TABLE T_ORDER_ENTRY CASCADE;

-- Sequence sequences
DROP SEQUENCE SQ_CITY CASCADE;
DROP SEQUENCE SQ_EVENT CASCADE;
DROP SEQUENCE SQ_LOCATION CASCADE;
DROP SEQUENCE SQ_ORDER CASCADE;
DROP SEQUENCE SQ_ORDER_ENTRY CASCADE;